let user_id = "3ea9c883-70f8-8490-f1c4-6a05ce996166";
let vehicles = [
  "13084493-98eb-7798-00fc-6a05d1b2fb41",
  "13bd1f33-2e60-4ced-a652-6a05d0fcb64e",
  "3c0e1902-5573-1a70-ea1a-6a05d163edcd",
  "65fa8d7c-48cd-6bf5-834d-6a05d050f840",
  "9d717847-8789-d0e5-dbf7-6a05d1257cac",
  "c2117e8a-f639-d0d3-9599-6a05d060192d",
];
let assigned_user_ids = [
  "3ea9c883-70f8-8490-f1c4-6a05ce996166",
  "160d3d78-1510-106e-f52a-6a05d2cfe938",
  "37b0e903-ecf4-7494-9c75-6a05d284e088",
  "445574d8-1490-61bb-234e-6a05d27bb9d2",
  "65ca1f3d-9564-d30d-db56-6a05d2c57c85",
  "c6070960-4952-b0c3-5f8b-6a05d227283e",
];


let lead_source = "kplimoservice.com";

let leads = [
  {
    first_name: "James",
    last_name: "Harrington",
    email: "james.harrington@gmail.com",
    phone: "2125550101",
    notes: "Please have water bottles available",
    pickup: "123 5th Ave, New York, NY 10001",
    destination: "JFK International Airport, Queens, NY 11430",
    pickup_date: "2026-06-15",
    service_type: "Airport",
    service_length: "3",
    passengers: "2",
  },
  {
    first_name: "Sophia",
    last_name: "Caldwell",
    email: "sophia.caldwell@yahoo.com",
    phone: "3105550182",
    notes: "Anniversary trip, please have decorations",
    pickup: "456 Sunset Blvd, Los Angeles, CA 90028",
    destination: "Santa Monica Pier, Santa Monica, CA 90401",
    pickup_date: "2026-06-20",
    service_type: "Night out on Town",
    service_length: "4",
    passengers: "4",
  },
  {
    first_name: "Ethan",
    last_name: "Morrison",
    email: "ethan.morrison@outlook.com",
    phone: "7735550144",
    notes: "Corporate meeting, need professional driver",
    pickup: "233 S Wacker Dr, Chicago, IL 60606",
    destination: "O'Hare International Airport, Chicago, IL 60666",
    pickup_date: "2026-07-02",
    service_type: "Corporate Event",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Olivia",
    last_name: "Bennett",
    email: "olivia.bennett@hotmail.com",
    phone: "7135550177",
    notes: "Bachelorette party, 8 ladies",
    pickup: "1600 Lamar St, Houston, TX 77010",
    destination: "Galveston Island, TX 77550",
    pickup_date: "2026-07-10",
    service_type: "Bachelorette Party",
    service_length: "6",
    passengers: "8",
  },
  {
    first_name: "Noah",
    last_name: "Fletcher",
    email: "noah.fletcher@gmail.com",
    phone: "6025550133",
    notes: "Golf tournament, clubs in trunk",
    pickup: "7700 E McCormick Pkwy, Scottsdale, AZ 85258",
    destination: "Troon North Golf Club, Scottsdale, AZ 85262",
    pickup_date: "2026-06-28",
    service_type: "Golf Outing",
    service_length: "5",
    passengers: "4",
  },
  {
    first_name: "Emma",
    last_name: "Sullivan",
    email: "emma.sullivan@gmail.com",
    phone: "2155550166",
    notes: "Wedding day, bride aboard",
    pickup: "300 N Broad St, Philadelphia, PA 19102",
    destination: "The Ritz-Carlton, Philadelphia, PA 19103",
    pickup_date: "2026-08-14",
    service_type: "Wedding",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Liam",
    last_name: "Patterson",
    email: "liam.patterson@yahoo.com",
    phone: "4045550198",
    notes: "Concert night, 3 stops",
    pickup: "190 Marietta St NW, Atlanta, GA 30303",
    destination: "State Farm Arena, Atlanta, GA 30303",
    pickup_date: "2026-07-19",
    service_type: "Concert",
    service_length: "3",
    passengers: "5",
  },
  {
    first_name: "Ava",
    last_name: "Reynolds",
    email: "ava.reynolds@outlook.com",
    phone: "5135550111",
    notes: "Family reunion, need large vehicle",
    pickup: "1 Paul Brown Stadium, Cincinnati, OH 45202",
    destination: "Kings Island, Mason, OH 45040",
    pickup_date: "2026-07-04",
    service_type: "Family Reunion",
    service_length: "5",
    passengers: "10",
  },
  {
    first_name: "Mason",
    last_name: "Griffin",
    email: "mason.griffin@gmail.com",
    phone: "3035550155",
    notes: "Airport drop early morning",
    pickup: "1700 Lincoln St, Denver, CO 80203",
    destination: "Denver International Airport, Denver, CO 80249",
    pickup_date: "2026-06-22",
    service_type: "Airport",
    service_length: "2",
    passengers: "2",
  },
  {
    first_name: "Isabella",
    last_name: "Hayes",
    email: "isabella.hayes@hotmail.com",
    phone: "7025550122",
    notes: "Casino night, round trip needed",
    pickup: "3600 S Las Vegas Blvd, Las Vegas, NV 89109",
    destination: "Red Rock Casino, Las Vegas, NV 89135",
    pickup_date: "2026-07-08",
    service_type: "Casino",
    service_length: "5",
    passengers: "6",
  },
  {
    first_name: "William",
    last_name: "Foster",
    email: "william.foster@gmail.com",
    phone: "5035550188",
    notes: "Wine tour for 4 couples",
    pickup: "150 SW Morrison St, Portland, OR 97204",
    destination: "Willamette Valley Vineyards, Turner, OR 97392",
    pickup_date: "2026-08-03",
    service_type: "Wine Tour",
    service_length: "6",
    passengers: "8",
  },
  {
    first_name: "Mia",
    last_name: "Simmons",
    email: "mia.simmons@yahoo.com",
    phone: "6175550144",
    notes: "Prom night, high school seniors",
    pickup: "25 School St, Boston, MA 02108",
    destination: "Marriott Copley Place, Boston, MA 02116",
    pickup_date: "2026-06-07",
    service_type: "Prom",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Benjamin",
    last_name: "Washington",
    email: "ben.washington@gmail.com",
    phone: "2025550177",
    notes: "Government conference transfer",
    pickup: "1600 Pennsylvania Ave NW, Washington, DC 20500",
    destination: "Ronald Reagan Airport, Arlington, VA 22202",
    pickup_date: "2026-07-15",
    service_type: "Transfer",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Charlotte",
    last_name: "Barnes",
    email: "charlotte.barnes@outlook.com",
    phone: "6155550199",
    notes: "Birthday dinner for 50th",
    pickup: "500 Commerce St, Nashville, TN 37203",
    destination: "Skull's Rainbow Room, Nashville, TN 37201",
    pickup_date: "2026-07-25",
    service_type: "Birthday",
    service_length: "4",
    passengers: "7",
  },
  {
    first_name: "Elijah",
    last_name: "Coleman",
    email: "elijah.coleman@hotmail.com",
    phone: "4695550133",
    notes: "Sports event, Cowboys game",
    pickup: "2909 Taylor St, Dallas, TX 75226",
    destination: "AT&T Stadium, Arlington, TX 76011",
    pickup_date: "2026-09-07",
    service_type: "Sports Event",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Amelia",
    last_name: "Jenkins",
    email: "amelia.jenkins@gmail.com",
    phone: "8585550166",
    notes: "Theme park trip for kids birthday",
    pickup: "500 Hotel Cir N, San Diego, CA 92108",
    destination: "Legoland California, Carlsbad, CA 92008",
    pickup_date: "2026-07-12",
    service_type: "Theme Park",
    service_length: "6",
    passengers: "5",
  },
  {
    first_name: "Alexander",
    last_name: "Perry",
    email: "alex.perry@yahoo.com",
    phone: "8135550144",
    notes: "Bachelor party, 10 guys",
    pickup: "1 Harbour Place, Tampa, FL 33602",
    destination: "Ybor City, Tampa, FL 33605",
    pickup_date: "2026-08-22",
    service_type: "Bachelor Party",
    service_length: "5",
    passengers: "10",
  },
  {
    first_name: "Harper",
    last_name: "Long",
    email: "harper.long@gmail.com",
    phone: "5025550188",
    notes: "Church retreat, senior group",
    pickup: "200 W Broadway, Louisville, KY 40202",
    destination: "Abbey of Gethsemani, Trappist, KY 40051",
    pickup_date: "2026-07-06",
    service_type: "Church Function",
    service_length: "4",
    passengers: "12",
  },
  {
    first_name: "Sebastian",
    last_name: "Ross",
    email: "sebastian.ross@outlook.com",
    phone: "5025550122",
    notes: "Over the road trip to conference",
    pickup: "100 N Kentucky Ave, Indianapolis, IN 46204",
    destination: "Cincinnati Convention Center, Cincinnati, OH 45202",
    pickup_date: "2026-08-10",
    service_type: "Over the Road",
    service_length: "3",
    passengers: "4",
  },
  {
    first_name: "Evelyn",
    last_name: "Howard",
    email: "evelyn.howard@hotmail.com",
    phone: "6505550155",
    notes: "Cruise transfer, early morning",
    pickup: "100 Moffett Blvd, Mountain View, CA 94043",
    destination: "Port of San Francisco, CA 94105",
    pickup_date: "2026-09-01",
    service_type: "Cruise Transfers",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Daniel",
    last_name: "Ward",
    email: "daniel.ward@gmail.com",
    phone: "2065550199",
    notes: "Convention shuttle for tech event",
    pickup: "800 Convention Place, Seattle, WA 98101",
    destination: "Washington State Convention Center, Seattle, WA 98101",
    pickup_date: "2026-08-18",
    service_type: "Convention",
    service_length: "3",
    passengers: "6",
  },
  {
    first_name: "Abigail",
    last_name: "Torres",
    email: "abigail.torres@yahoo.com",
    phone: "3055550133",
    notes: "Homecoming dance",
    pickup: "1200 NW 7th Ave, Miami, FL 33136",
    destination: "Fontainebleau Miami Beach, FL 33140",
    pickup_date: "2026-10-03",
    service_type: "Homecoming",
    service_length: "4",
    passengers: "4",
  },
  {
    first_name: "Matthew",
    last_name: "Nguyen",
    email: "matthew.nguyen@gmail.com",
    phone: "5125550177",
    notes: "School trip to museum",
    pickup: "2400 E 6th St, Austin, TX 78702",
    destination: "Bullock Texas State History Museum, Austin, TX 78701",
    pickup_date: "2026-06-25",
    service_type: "School Trip",
    service_length: "3",
    passengers: "15",
  },
  {
    first_name: "Emily",
    last_name: "Rivera",
    email: "emily.rivera@outlook.com",
    phone: "6025550144",
    notes: "Construction crew shuttle",
    pickup: "4000 N 7th St, Phoenix, AZ 85014",
    destination: "Sky Harbor International Airport, Phoenix, AZ 85034",
    pickup_date: "2026-07-03",
    service_type: "Construction Shuttle",
    service_length: "2",
    passengers: "8",
  },
  {
    first_name: "Michael",
    last_name: "Sanchez",
    email: "michael.sanchez@hotmail.com",
    phone: "5055550188",
    notes: "General day trip, sightseeing",
    pickup: "505 Marquette Ave, Minneapolis, MN 55402",
    destination: "Mall of America, Bloomington, MN 55425",
    pickup_date: "2026-07-20",
    service_type: "General Day Trip",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Elizabeth",
    last_name: "Morris",
    email: "elizabeth.morris@gmail.com",
    phone: "7025550155",
    notes: "Wedding Wire referral, bride",
    pickup: "3655 S Durango Dr, Las Vegas, NV 89147",
    destination: "Bellagio Hotel, Las Vegas, NV 89109",
    pickup_date: "2026-09-12",
    service_type: "Wedding Wire",
    service_length: "3",
    passengers: "5",
  },
  {
    first_name: "Aiden",
    last_name: "Murphy",
    email: "aiden.murphy@yahoo.com",
    phone: "6175550122",
    notes: "Airport pickup from Logan",
    pickup: "One International Place, Boston, MA 02110",
    destination: "Logan International Airport, Boston, MA 02128",
    pickup_date: "2026-06-30",
    service_type: "Airport",
    service_length: "2",
    passengers: "2",
  },
  {
    first_name: "Sofia",
    last_name: "Cook",
    email: "sofia.cook@gmail.com",
    phone: "4145550199",
    notes: "Birthday celebration, sweet 16",
    pickup: "310 W Wisconsin Ave, Milwaukee, WI 53203",
    destination: "American Family Field, Milwaukee, WI 53214",
    pickup_date: "2026-08-08",
    service_type: "Birthday",
    service_length: "4",
    passengers: "8",
  },
  {
    first_name: "Jackson",
    last_name: "Rogers",
    email: "jackson.rogers@outlook.com",
    phone: "9165550133",
    notes: "Corporate event downtown",
    pickup: "400 Capitol Mall, Sacramento, CA 95814",
    destination: "SAFE Credit Union Convention Center, Sacramento, CA 95814",
    pickup_date: "2026-07-14",
    service_type: "Corporate Event",
    service_length: "3",
    passengers: "6",
  },
  {
    first_name: "Scarlett",
    last_name: "Reed",
    email: "scarlett.reed@hotmail.com",
    phone: "5025550177",
    notes: "Concert with friends",
    pickup: "600 W Pete Rose Way, Cincinnati, OH 45203",
    destination: "PNC Pavilion, Cincinnati, OH 45202",
    pickup_date: "2026-08-01",
    service_type: "Concert",
    service_length: "4",
    passengers: "4",
  },
  {
    first_name: "Lucas",
    last_name: "Bailey",
    email: "lucas.bailey@gmail.com",
    phone: "3145550144",
    notes: "Shuttle for office team",
    pickup: "1 Memorial Dr, St. Louis, MO 63102",
    destination: "Busch Stadium, St. Louis, MO 63102",
    pickup_date: "2026-07-17",
    service_type: "Shuttle Service",
    service_length: "2",
    passengers: "9",
  },
  {
    first_name: "Madison",
    last_name: "Bell",
    email: "madison.bell@yahoo.com",
    phone: "6175550188",
    notes: "Cruise transfer, family of 4",
    pickup: "100 Cambridge St, Boston, MA 02114",
    destination: "Black Falcon Cruise Terminal, Boston, MA 02210",
    pickup_date: "2026-09-05",
    service_type: "Cruise Transfers",
    service_length: "2",
    passengers: "4",
  },
  {
    first_name: "Henry",
    last_name: "Adams",
    email: "henry.adams@gmail.com",
    phone: "4045550122",
    notes: "Golf outing with clients",
    pickup: "265 Park Ave W NW, Atlanta, GA 30313",
    destination: "TPC Sugarloaf, Duluth, GA 30097",
    pickup_date: "2026-07-26",
    service_type: "Golf Outing",
    service_length: "5",
    passengers: "4",
  },
  {
    first_name: "Chloe",
    last_name: "Nelson",
    email: "chloe.nelson@outlook.com",
    phone: "7135550199",
    notes: "Wine tasting weekend",
    pickup: "2800 Post Oak Blvd, Houston, TX 77056",
    destination: "Bryan, TX 77801",
    pickup_date: "2026-08-29",
    service_type: "Wine Tour",
    service_length: "6",
    passengers: "6",
  },
  {
    first_name: "Logan",
    last_name: "Carter",
    email: "logan.carter@hotmail.com",
    phone: "2025550133",
    notes: "Transfer from Union Station",
    pickup: "50 Massachusetts Ave NE, Washington, DC 20002",
    destination: "Baltimore Washington Airport, Baltimore, MD 21240",
    pickup_date: "2026-07-09",
    service_type: "Transfer",
    service_length: "2",
    passengers: "2",
  },
  {
    first_name: "Penelope",
    last_name: "Mitchell",
    email: "penelope.mitchell@gmail.com",
    phone: "6025550177",
    notes: "Prom night, needs red carpet",
    pickup: "3800 N Central Ave, Phoenix, AZ 85012",
    destination: "Sheraton Grand at Wild Horse Pass, Chandler, AZ 85226",
    pickup_date: "2026-05-30",
    service_type: "Prom",
    service_length: "4",
    passengers: "4",
  },
  {
    first_name: "Owen",
    last_name: "Perez",
    email: "owen.perez@yahoo.com",
    phone: "2125550144",
    notes: "Sports event, Yankees game",
    pickup: "200 W 34th St, New York, NY 10001",
    destination: "Yankee Stadium, Bronx, NY 10451",
    pickup_date: "2026-09-15",
    service_type: "Sports Event",
    service_length: "3",
    passengers: "6",
  },
  {
    first_name: "Layla",
    last_name: "Roberts",
    email: "layla.roberts@gmail.com",
    phone: "3035550188",
    notes: "Theme park for family",
    pickup: "1675 Larimer St, Denver, CO 80202",
    destination: "Elitch Gardens, Denver, CO 80204",
    pickup_date: "2026-07-04",
    service_type: "Theme Park",
    service_length: "5",
    passengers: "5",
  },
  {
    first_name: "Carter",
    last_name: "Turner",
    email: "carter.turner@outlook.com",
    phone: "8135550122",
    notes: "Bachelor party bar crawl",
    pickup: "400 N Ashley Dr, Tampa, FL 33602",
    destination: "Hyde Park Village, Tampa, FL 33606",
    pickup_date: "2026-08-15",
    service_type: "Bachelor Party",
    service_length: "6",
    passengers: "8",
  },
  {
    first_name: "Riley",
    last_name: "Phillips",
    email: "riley.phillips@hotmail.com",
    phone: "4155550199",
    notes: "Convention attendee group",
    pickup: "747 Howard St, San Francisco, CA 94103",
    destination: "Moscone Center, San Francisco, CA 94103",
    pickup_date: "2026-09-22",
    service_type: "Convention",
    service_length: "3",
    passengers: "7",
  },
  {
    first_name: "Wyatt",
    last_name: "Campbell",
    email: "wyatt.campbell@gmail.com",
    phone: "5025550133",
    notes: "Family reunion picnic",
    pickup: "700 W Main St, Louisville, KY 40202",
    destination: "Cherokee Park, Louisville, KY 40204",
    pickup_date: "2026-07-19",
    service_type: "Family Reunion",
    service_length: "4",
    passengers: "12",
  },
  {
    first_name: "Nora",
    last_name: "Parker",
    email: "nora.parker@yahoo.com",
    phone: "7135550166",
    notes: "Airport early morning flight",
    pickup: "5000 Westheimer Rd, Houston, TX 77056",
    destination: "Houston Hobby Airport, Houston, TX 77061",
    pickup_date: "2026-06-18",
    service_type: "Airport",
    service_length: "2",
    passengers: "2",
  },
  {
    first_name: "Eli",
    last_name: "Evans",
    email: "eli.evans@gmail.com",
    phone: "6155550144",
    notes: "Church conference, senior group",
    pickup: "1000 Broadway, Nashville, TN 37203",
    destination: "Opryland Hotel, Nashville, TN 37214",
    pickup_date: "2026-08-24",
    service_type: "Church Function",
    service_length: "3",
    passengers: "10",
  },
  {
    first_name: "Lily",
    last_name: "Edwards",
    email: "lily.edwards@outlook.com",
    phone: "5035550177",
    notes: "School field trip",
    pickup: "1900 SW 4th Ave, Portland, OR 97201",
    destination: "Oregon Museum of Science, Portland, OR 97232",
    pickup_date: "2026-06-12",
    service_type: "School Trip",
    service_length: "3",
    passengers: "20",
  },
  {
    first_name: "Grayson",
    last_name: "Collins",
    email: "grayson.collins@hotmail.com",
    phone: "4025550122",
    notes: "Homecoming dance, limousine style",
    pickup: "1600 Dodge St, Omaha, NE 68102",
    destination: "Embassy Suites Omaha, NE 68154",
    pickup_date: "2026-10-10",
    service_type: "Homecoming",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Zoey",
    last_name: "Stewart",
    email: "zoey.stewart@gmail.com",
    phone: "2065550155",
    notes: "Wine tour in wine country",
    pickup: "600 Pine St, Seattle, WA 98101",
    destination: "Chateau Ste. Michelle, Woodinville, WA 98072",
    pickup_date: "2026-09-06",
    service_type: "Wine Tour",
    service_length: "5",
    passengers: "6",
  },
  {
    first_name: "Julian",
    last_name: "Sanchez",
    email: "julian.sanchez@yahoo.com",
    phone: "5125550199",
    notes: "Night out with colleagues",
    pickup: "6th St & Congress Ave, Austin, TX 78701",
    destination: "Rainey Street District, Austin, TX 78701",
    pickup_date: "2026-07-11",
    service_type: "Night out on Town",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Hannah",
    last_name: "Morris",
    email: "hannah.morris@gmail.com",
    phone: "7025550133",
    notes: "Bachelorette spa weekend",
    pickup: "2655 S Maryland Pkwy, Las Vegas, NV 89109",
    destination: "Spa at ARIA, Las Vegas, NV 89158",
    pickup_date: "2026-08-20",
    service_type: "Bachelorette Party",
    service_length: "5",
    passengers: "7",
  },
  {
    first_name: "Caleb",
    last_name: "Rogers",
    email: "caleb.rogers@outlook.com",
    phone: "3055550166",
    notes: "Transfer to seaport",
    pickup: "200 Biscayne Blvd, Miami, FL 33132",
    destination: "PortMiami, Miami, FL 33132",
    pickup_date: "2026-09-10",
    service_type: "Cruise Transfers",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Stella",
    last_name: "Reed",
    email: "stella.reed@hotmail.com",
    phone: "6155550144",
    notes: "Birthday party for 30th",
    pickup: "230 5th Ave S, Nashville, TN 37203",
    destination: "Assembly Food Hall, Nashville, TN 37219",
    pickup_date: "2026-08-07",
    service_type: "Birthday",
    service_length: "4",
    passengers: "9",
  },
  {
    first_name: "Isaac",
    last_name: "Cook",
    email: "isaac.cook@gmail.com",
    phone: "2025550188",
    notes: "Shuttle for government visitors",
    pickup: "600 E St NW, Washington, DC 20004",
    destination: "Dulles International Airport, Dulles, VA 20166",
    pickup_date: "2026-07-22",
    service_type: "Shuttle Service",
    service_length: "3",
    passengers: "4",
  },
  {
    first_name: "Violet",
    last_name: "Morgan",
    email: "violet.morgan@yahoo.com",
    phone: "3145550155",
    notes: "General day trip for tourists",
    pickup: "700 Market St, St. Louis, MO 63101",
    destination: "Anheuser-Busch Brewery, St. Louis, MO 63118",
    pickup_date: "2026-07-28",
    service_type: "General Day Trip",
    service_length: "3",
    passengers: "6",
  },
  {
    first_name: "Christian",
    last_name: "Bell",
    email: "christian.bell@gmail.com",
    phone: "6025550199",
    notes: "Over the road to convention",
    pickup: "1 E Washington St, Phoenix, AZ 85004",
    destination: "Tucson Convention Center, Tucson, AZ 85701",
    pickup_date: "2026-08-13",
    service_type: "Over the Road",
    service_length: "2",
    passengers: "5",
  },
  {
    first_name: "Aurora",
    last_name: "Murphy",
    email: "aurora.murphy@outlook.com",
    phone: "4045550133",
    notes: "Wedding ceremony transfer",
    pickup: "1 CNN Center, Atlanta, GA 30303",
    destination: "Swan House, Atlanta, GA 30305",
    pickup_date: "2026-09-19",
    service_type: "Wedding",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Dominic",
    last_name: "Bailey",
    email: "dominic.bailey@hotmail.com",
    phone: "7735550166",
    notes: "Corporate client pickup",
    pickup: "875 N Michigan Ave, Chicago, IL 60611",
    destination: "Midway Airport, Chicago, IL 60638",
    pickup_date: "2026-07-01",
    service_type: "Corporate Event",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Claire",
    last_name: "Rivera",
    email: "claire.rivera@gmail.com",
    phone: "2125550133",
    notes: "Concert at Madison Square Garden",
    pickup: "140 W 42nd St, New York, NY 10036",
    destination: "Madison Square Garden, New York, NY 10001",
    pickup_date: "2026-08-09",
    service_type: "Concert",
    service_length: "3",
    passengers: "4",
  },
  {
    first_name: "Josiah",
    last_name: "Cooper",
    email: "josiah.cooper@yahoo.com",
    phone: "4695550177",
    notes: "Sports event, Mavericks game",
    pickup: "1717 Main St, Dallas, TX 75201",
    destination: "American Airlines Center, Dallas, TX 75219",
    pickup_date: "2026-11-05",
    service_type: "Sports Event",
    service_length: "3",
    passengers: "5",
  },
  {
    first_name: "Naomi",
    last_name: "Richardson",
    email: "naomi.richardson@gmail.com",
    phone: "5135550155",
    notes: "Casino trip with friends",
    pickup: "525 Vine St, Cincinnati, OH 45202",
    destination: "Belterra Park, Cincinnati, OH 45230",
    pickup_date: "2026-07-31",
    service_type: "Casino",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Thomas",
    last_name: "Cox",
    email: "thomas.cox@outlook.com",
    phone: "5035550122",
    notes: "Airport transfer, early departure",
    pickup: "900 SW 5th Ave, Portland, OR 97204",
    destination: "Portland International Airport, Portland, OR 97218",
    pickup_date: "2026-06-19",
    service_type: "Airport",
    service_length: "2",
    passengers: "2",
  },
  {
    first_name: "Ellie",
    last_name: "Howard",
    email: "ellie.howard@hotmail.com",
    phone: "2155550199",
    notes: "Bachelorette dinner party",
    pickup: "1234 Walnut St, Philadelphia, PA 19107",
    destination: "Zahav Restaurant, Philadelphia, PA 19106",
    pickup_date: "2026-08-16",
    service_type: "Bachelorette Party",
    service_length: "4",
    passengers: "8",
  },
  {
    first_name: "Adrian",
    last_name: "Ward",
    email: "adrian.ward@gmail.com",
    phone: "8585550133",
    notes: "Golf tournament transport",
    pickup: "333 W Harbor Dr, San Diego, CA 92101",
    destination: "Torrey Pines Golf Course, La Jolla, CA 92037",
    pickup_date: "2026-07-23",
    service_type: "Golf Outing",
    service_length: "5",
    passengers: "4",
  },
  {
    first_name: "Hazel",
    last_name: "Torres",
    email: "hazel.torres@yahoo.com",
    phone: "6505550177",
    notes: "Theme park for child's birthday",
    pickup: "200 Portola Ave, San Jose, CA 95112",
    destination: "California's Great America, Santa Clara, CA 95054",
    pickup_date: "2026-08-02",
    service_type: "Theme Park",
    service_length: "5",
    passengers: "6",
  },
  {
    first_name: "Jonathan",
    last_name: "Peterson",
    email: "jonathan.peterson@gmail.com",
    phone: "4145550155",
    notes: "Shuttle for construction crew",
    pickup: "233 E Michigan St, Milwaukee, WI 53202",
    destination: "Fiserv Forum Construction Site, Milwaukee, WI 53203",
    pickup_date: "2026-07-07",
    service_type: "Construction Shuttle",
    service_length: "2",
    passengers: "7",
  },
  {
    first_name: "Luna",
    last_name: "Gray",
    email: "luna.gray@outlook.com",
    phone: "5025550188",
    notes: "Prom night, needs luxury vehicle",
    pickup: "500 W Broadway, Louisville, KY 40202",
    destination: "Galt House Hotel, Louisville, KY 40202",
    pickup_date: "2026-05-16",
    service_type: "Prom",
    service_length: "3",
    passengers: "4",
  },
  {
    first_name: "Andrew",
    last_name: "Ramirez",
    email: "andrew.ramirez@hotmail.com",
    phone: "3055550144",
    notes: "Night out in South Beach",
    pickup: "801 Brickell Ave, Miami, FL 33131",
    destination: "LIV Nightclub, Miami Beach, FL 33139",
    pickup_date: "2026-07-18",
    service_type: "Night out on Town",
    service_length: "5",
    passengers: "6",
  },
  {
    first_name: "Penelope",
    last_name: "Hughes",
    email: "penelope.hughes@gmail.com",
    phone: "3145550199",
    notes: "Family day trip to winery",
    pickup: "200 N 4th St, St. Louis, MO 63102",
    destination: "Augusta Winery, Augusta, MO 63332",
    pickup_date: "2026-09-13",
    service_type: "General Day Trip",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Ezra",
    last_name: "Price",
    email: "ezra.price@yahoo.com",
    phone: "6155550133",
    notes: "Church group outing",
    pickup: "400 Broadway, Nashville, TN 37201",
    destination: "Radnor Lake State Park, Nashville, TN 37220",
    pickup_date: "2026-07-27",
    service_type: "Church Function",
    service_length: "3",
    passengers: "11",
  },
  {
    first_name: "Paisley",
    last_name: "Bennett",
    email: "paisley.bennett@gmail.com",
    phone: "2065550177",
    notes: "Convention group from hotel",
    pickup: "1900 5th Ave, Seattle, WA 98101",
    destination: "Seattle Convention Center, Seattle, WA 98101",
    pickup_date: "2026-09-29",
    service_type: "Convention",
    service_length: "3",
    passengers: "8",
  },
  {
    first_name: "Zachary",
    last_name: "Foster",
    email: "zachary.foster@outlook.com",
    phone: "7025550155",
    notes: "Wedding Wire client, cocktail hour",
    pickup: "3475 S Las Vegas Blvd, Las Vegas, NV 89109",
    destination: "The Venetian, Las Vegas, NV 89109",
    pickup_date: "2026-10-04",
    service_type: "Wedding Wire",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Savannah",
    last_name: "Bryant",
    email: "savannah.bryant@hotmail.com",
    phone: "4025550188",
    notes: "Airport departure, early flight",
    pickup: "13655 Millard Ave, Omaha, NE 68137",
    destination: "Eppley Airfield, Omaha, NE 68110",
    pickup_date: "2026-06-26",
    service_type: "Airport",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Nathan",
    last_name: "Alexander",
    email: "nathan.alexander@gmail.com",
    phone: "2125550177",
    notes: "Sports event, Knicks game",
    pickup: "123 W 57th St, New York, NY 10019",
    destination: "Madison Square Garden, New York, NY 10001",
    pickup_date: "2026-11-12",
    service_type: "Sports Event",
    service_length: "3",
    passengers: "4",
  },
  {
    first_name: "Brooklyn",
    last_name: "James",
    email: "brooklyn.james@yahoo.com",
    phone: "4045550166",
    notes: "Birthday dinner for twins",
    pickup: "130 Luckie St, Atlanta, GA 30303",
    destination: "Ponce City Market, Atlanta, GA 30308",
    pickup_date: "2026-08-30",
    service_type: "Birthday",
    service_length: "4",
    passengers: "8",
  },
  {
    first_name: "Isaiah",
    last_name: "Watson",
    email: "isaiah.watson@gmail.com",
    phone: "3035550155",
    notes: "Transfer to conference center",
    pickup: "2000 Welton St, Denver, CO 80205",
    destination: "Colorado Convention Center, Denver, CO 80202",
    pickup_date: "2026-09-03",
    service_type: "Transfer",
    service_length: "2",
    passengers: "4",
  },
  {
    first_name: "Aubrey",
    last_name: "Brooks",
    email: "aubrey.brooks@outlook.com",
    phone: "4695550199",
    notes: "Homecoming at local venue",
    pickup: "3000 Blackburn St, Dallas, TX 75204",
    destination: "AT&T Performing Arts Center, Dallas, TX 75201",
    pickup_date: "2026-10-17",
    service_type: "Homecoming",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Gabriel",
    last_name: "Kelly",
    email: "gabriel.kelly@hotmail.com",
    phone: "7735550133",
    notes: "Over the road business trip",
    pickup: "100 W Monroe St, Chicago, IL 60603",
    destination: "Indianapolis Convention Center, Indianapolis, IN 46225",
    pickup_date: "2026-08-05",
    service_type: "Over the Road",
    service_length: "3",
    passengers: "4",
  },
  {
    first_name: "Bella",
    last_name: "Sanders",
    email: "bella.sanders@gmail.com",
    phone: "5125550166",
    notes: "School trip to state capitol",
    pickup: "1100 Congress Ave, Austin, TX 78701",
    destination: "Texas State Cemetery, Austin, TX 78702",
    pickup_date: "2026-06-09",
    service_type: "School Trip",
    service_length: "3",
    passengers: "18",
  },
  {
    first_name: "Ryan",
    last_name: "Price",
    email: "ryan.price@yahoo.com",
    phone: "8135550188",
    notes: "Bachelor party boat transfer",
    pickup: "601 Channelside Dr, Tampa, FL 33602",
    destination: "Dunedin Marina, Dunedin, FL 34698",
    pickup_date: "2026-09-20",
    service_type: "Bachelor Party",
    service_length: "5",
    passengers: "9",
  },
  {
    first_name: "Aria",
    last_name: "Bennett",
    email: "aria.bennett@gmail.com",
    phone: "6175550133",
    notes: "Cruise transfer for family",
    pickup: "100 Federal St, Boston, MA 02110",
    destination: "Boston Cruise Terminal, Boston, MA 02210",
    pickup_date: "2026-10-01",
    service_type: "Cruise Transfers",
    service_length: "2",
    passengers: "5",
  },
  {
    first_name: "Brandon",
    last_name: "Wood",
    email: "brandon.wood@outlook.com",
    phone: "4155550177",
    notes: "Wine tour for group",
    pickup: "50 3rd St, San Francisco, CA 94103",
    destination: "Napa Valley Wine Train, Napa, CA 94559",
    pickup_date: "2026-09-27",
    service_type: "Wine Tour",
    service_length: "6",
    passengers: "8",
  },
  {
    first_name: "Genesis",
    last_name: "Nguyen",
    email: "genesis.nguyen@hotmail.com",
    phone: "3145550166",
    notes: "Night out downtown",
    pickup: "100 N Broadway, St. Louis, MO 63102",
    destination: "The Grove, St. Louis, MO 63110",
    pickup_date: "2026-08-23",
    service_type: "Night out on Town",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Dylan",
    last_name: "Flores",
    email: "dylan.flores@gmail.com",
    phone: "5055550144",
    notes: "Family reunion at park",
    pickup: "900 Nicollet Mall, Minneapolis, MN 55402",
    destination: "Minnehaha Park, Minneapolis, MN 55417",
    pickup_date: "2026-07-05",
    service_type: "Family Reunion",
    service_length: "4",
    passengers: "14",
  },
  {
    first_name: "Aaliyah",
    last_name: "Washington",
    email: "aaliyah.washington@yahoo.com",
    phone: "5025550155",
    notes: "Corporate event transfer",
    pickup: "500 W Jefferson St, Louisville, KY 40202",
    destination: "Louisville Marriott Downtown, KY 40202",
    pickup_date: "2026-08-11",
    service_type: "Corporate Event",
    service_length: "3",
    passengers: "5",
  },
  {
    first_name: "Jeremiah",
    last_name: "Cole",
    email: "jeremiah.cole@gmail.com",
    phone: "6025550166",
    notes: "Golf outing with partners",
    pickup: "2 N Central Ave, Phoenix, AZ 85004",
    destination: "Wigwam Golf Club, Litchfield Park, AZ 85340",
    pickup_date: "2026-08-26",
    service_type: "Golf Outing",
    service_length: "5",
    passengers: "4",
  },
  {
    first_name: "Peyton",
    last_name: "Richardson",
    email: "peyton.richardson@outlook.com",
    phone: "2155550144",
    notes: "Wedding ceremony and reception",
    pickup: "200 S Broad St, Philadelphia, PA 19102",
    destination: "The Crystal Tea Room, Philadelphia, PA 19107",
    pickup_date: "2026-10-11",
    service_type: "Wedding",
    service_length: "5",
    passengers: "7",
  },
  {
    first_name: "Landon",
    last_name: "Martinez",
    email: "landon.martinez@hotmail.com",
    phone: "4025550177",
    notes: "Shuttle for airport workers",
    pickup: "1100 N 24th St, Omaha, NE 68110",
    destination: "Eppley Airfield Employee Lot, Omaha, NE 68110",
    pickup_date: "2026-07-16",
    service_type: "Shuttle Service",
    service_length: "2",
    passengers: "6",
  },
  {
    first_name: "Sadie",
    last_name: "Hernandez",
    email: "sadie.hernandez@gmail.com",
    phone: "3035550144",
    notes: "Casino trip girls night",
    pickup: "1145 17th St, Denver, CO 80202",
    destination: "Isle Casino Hotel Black Hawk, CO 80422",
    pickup_date: "2026-08-28",
    service_type: "Casino",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Hudson",
    last_name: "Young",
    email: "hudson.young@yahoo.com",
    phone: "9165550188",
    notes: "Convention tech shuttle",
    pickup: "1020 L St, Sacramento, CA 95814",
    destination: "SAFE Credit Union Convention Center, Sacramento, CA 95814",
    pickup_date: "2026-10-08",
    service_type: "Convention",
    service_length: "3",
    passengers: "7",
  },
  {
    first_name: "Leah",
    last_name: "Allen",
    email: "leah.allen@gmail.com",
    phone: "2025550166",
    notes: "Airport pickup for delegation",
    pickup: "1801 L St NW, Washington, DC 20036",
    destination: "Ronald Reagan Airport, Arlington, VA 22202",
    pickup_date: "2026-07-24",
    service_type: "Airport",
    service_length: "2",
    passengers: "4",
  },
  {
    first_name: "Levi",
    last_name: "King",
    email: "levi.king@outlook.com",
    phone: "5035550155",
    notes: "Concert at outdoor amphitheater",
    pickup: "1030 SW Broadway, Portland, OR 97205",
    destination: "Oregon Zoo Amphitheater, Portland, OR 97221",
    pickup_date: "2026-08-17",
    service_type: "Concert",
    service_length: "4",
    passengers: "5",
  },
  {
    first_name: "Addison",
    last_name: "Wright",
    email: "addison.wright@hotmail.com",
    phone: "7135550144",
    notes: "Corporate gala event",
    pickup: "1600 Smith St, Houston, TX 77002",
    destination: "NRG Center, Houston, TX 77054",
    pickup_date: "2026-09-18",
    service_type: "Corporate Event",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Easton",
    last_name: "Scott",
    email: "easton.scott@gmail.com",
    phone: "6155550188",
    notes: "Night out, bachelor send off",
    pickup: "500 Church St, Nashville, TN 37219",
    destination: "Printer's Alley, Nashville, TN 37201",
    pickup_date: "2026-09-25",
    service_type: "Night out on Town",
    service_length: "5",
    passengers: "7",
  },
  {
    first_name: "Caroline",
    last_name: "Green",
    email: "caroline.green@yahoo.com",
    phone: "4145550133",
    notes: "School trip science center",
    pickup: "800 W Wells St, Milwaukee, WI 53233",
    destination: "Discovery World, Milwaukee, WI 53202",
    pickup_date: "2026-06-17",
    service_type: "School Trip",
    service_length: "3",
    passengers: "16",
  },
  {
    first_name: "Miles",
    last_name: "Baker",
    email: "miles.baker@gmail.com",
    phone: "4695550155",
    notes: "Sports event, Rangers game",
    pickup: "100 Commerce St, Dallas, TX 75202",
    destination: "Globe Life Field, Arlington, TX 76011",
    pickup_date: "2026-09-23",
    service_type: "Sports Event",
    service_length: "3",
    passengers: "5",
  },
  {
    first_name: "Willow",
    last_name: "Adams",
    email: "willow.adams@outlook.com",
    phone: "7025550188",
    notes: "Transfer to wedding venue",
    pickup: "3900 Paradise Rd, Las Vegas, NV 89169",
    destination: "Chapel of the Flowers, Las Vegas, NV 89101",
    pickup_date: "2026-10-16",
    service_type: "Transfer",
    service_length: "2",
    passengers: "3",
  },
  {
    first_name: "Jaxon",
    last_name: "Nelson",
    email: "jaxon.nelson@hotmail.com",
    phone: "2065550144",
    notes: "Birthday surprise trip",
    pickup: "1000 1st Ave, Seattle, WA 98104",
    destination: "Snoqualmie Falls, Snoqualmie, WA 98065",
    pickup_date: "2026-09-07",
    service_type: "Birthday",
    service_length: "4",
    passengers: "6",
  },
  {
    first_name: "Kinsley",
    last_name: "Carter",
    email: "kinsley.carter@gmail.com",
    phone: "6025550133",
    notes: "Bachelorette cooking class trip",
    pickup: "5000 N 7th Ave, Phoenix, AZ 85013",
    destination: "Sur La Table, Scottsdale, AZ 85251",
    pickup_date: "2026-09-14",
    service_type: "Bachelorette Party",
    service_length: "3",
    passengers: "7",
  },
];
;



/** SuiteCRM CustomEntryPoint (same as config/api.php saveLead). */
const ENTRY_POINT_URL =
  "https://zabrin.xyz/limogen/index.php?entryPoint=CustomEntryPoint";

function pickRandomVehicleId() {
  return vehicles[Math.floor(Math.random() * vehicles.length)];
}

function pickRandomAssignedUserId() {
  return assigned_user_ids[Math.floor(Math.random() * assigned_user_ids.length)];
}
/**
 * POST fields expected by CustomEntryPoint::save_lead ($data / $_POST).
 * vehicle_id is randomized per request from `vehicles`.
 */
function buildSaveLeadBody(lead) {
  var params = new URLSearchParams();
  params.set("action", "save_lead");
  params.set("first_name", lead.first_name);
  params.set("last_name", lead.last_name);
  params.set("email", lead.email);
  params.set("lead_source", lead_source);
  params.set("phone", lead.phone);
  params.set("notes", lead.notes != null ? String(lead.notes) : "");
  params.set("pickup", lead.pickup);
  params.set("destination", lead.destination);
  params.set("pickup_date", lead.pickup_date);
  params.set("vehicle_id", pickRandomVehicleId());
  params.set("service_type", lead.service_type);
  params.set("service_length", String(lead.service_length));
  params.set("passengers", String(lead.passengers));
  params.set("owner_id", user_id);
  params.set("assigned_user_id", pickRandomAssignedUserId());
  if (lead.lead_source) {
    params.set("lead_source", lead.lead_source);
  }
  return params;
}

/**
 * POST each lead to the entry point (Node 18+ for global fetch).
 * @param {{ delayMs?: number, limit?: number }} options
 */
async function postLeadsToSuiteCRM(options) {
  options = options || {};
  var delayMs = options.delayMs != null ? options.delayMs : 400;
  var limit = options.limit;
  var list =
    typeof limit === "number" && limit > 0 ? leads.slice(0, limit) : leads;
  var results = [];
  for (var i = 0; i < list.length; i++) {
    var lead = list[i];
    var formBody = buildSaveLeadBody(lead);
    var vehicleIdUsed = formBody.get("vehicle_id");
    var res = await fetch(ENTRY_POINT_URL, {
      method: "POST",
      headers: {
        Accept: "application/json",
      },
      body: formBody,
    });
    var raw = await res.text();
    var json;
    try {
      json = JSON.parse(raw);
    } catch (e) {
      json = { success: false, message: "Non-JSON response", raw: raw.slice(0, 500) };
    }
    results.push({
      index: i,
      last_name: lead.last_name,
      status: res.status,
      vehicle_id_used: vehicleIdUsed,
      json: json,
    });
    console.log(
      "[" + (i + 1) + "/" + list.length + "]",
      lead.last_name,
      "vehicle:",
      vehicleIdUsed.slice(0, 13) + "…",
      res.status,
      json.success === true ? "success" : (json.message || raw).toString().slice(0, 120)
    );
    if (json.success === true && json.id) {
      console.log("  lead id:", json.id);
    }
    if (i < list.length - 1 && delayMs > 0) {
      await new Promise(function (r) {
        setTimeout(r, delayMs);
      });
    }
  }
  return results;
}

var isNode =
  typeof process !== "undefined" &&
  process.versions &&
  process.versions.node;

if (isNode) {
  var limIdx = process.argv.indexOf("--limit");
  var lim =
    limIdx >= 0 && process.argv[limIdx + 1]
      ? parseInt(process.argv[limIdx + 1], 10)
      : NaN;
  postLeadsToSuiteCRM({
    limit: Number.isFinite(lim) ? lim : undefined,
  })
    .then(function () {
      process.exit(0);
    })
    .catch(function (e) {
      console.error(e);
      process.exit(1);
    });
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    ENTRY_POINT_URL: ENTRY_POINT_URL,
    pickRandomVehicleId: pickRandomVehicleId,
    buildSaveLeadBody: buildSaveLeadBody,
    postLeadsToSuiteCRM: postLeadsToSuiteCRM,
  };
}
